version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      - DB_HOST:mongodb
      - DB_PORT-27017
      - DB_NAME=todo
    volumes:
      - .:/app
      - /app/node_modules
  
  mongodb:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: