name: Todo CI
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          run: action/checkout@v3
        - name: Byild Docker image
          run: docker build -t todo-app:latest ./todo-app